"""Pocklington certificates from a PARTIAL factorisation, plus smooth generation.

POCKLINGTON.  Let N-1 = F*R with gcd(F,R) = 1, F fully factored, F > sqrt(N).
If for every prime r | F there is a_r with
        a_r^(N-1) = 1 (mod N)   and   gcd(a_r^((N-1)/r) - 1, N) = 1,
then N is prime.  Only F need be factored -- R may be an unfactored monster.

WHY THAT RESCUES THE CHAIN.  The Lucas route needed q +- 1 completely factored,
and rho stalls near q ~ 1e22.  Instead CONSTRUCT q: take N smooth (a product of
small primes, so factored by construction) with N = 0 mod 4, and set q = N + 1.
Then
  * q - 1 = N is factored, so q itself is Pocklington-certified for free
    (F = N = q-1 > sqrt(q)), however large q gets;
  * p = (q^2+1)/2 has p - 1 = (q-1)(q+1)/2 = N * (N/2 + 1), and
    F = N ~ sqrt(2p) > sqrt(p), so N ALONE certifies p -- the cofactor
    N/2 + 1 is never factored;
  * N = 0 mod 4 forces gcd(N, N/2+1) = 1: any common divisor d divides
    N - 2(N/2+1) = -2, and N/2+1 is odd, so d = 1.
No factorisation is performed anywhere in the loop.
"""
from math import gcd

MR_LIMIT = 3317044064679887385961981
_MR_BASES = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41)


def is_prime_mr(n: int) -> bool:
    """Deterministic below MR_LIMIT; above it, a filter with no false negatives."""
    if n < 2:
        return False
    for p in _MR_BASES:
        if n % p == 0:
            return n == p
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in _MR_BASES:
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def pocklington_witnesses(N: int, rs, max_a: int = 500):
    """Witnesses a_r for each prime r in rs, or None. rs are the primes of F."""
    out = {}
    for r in rs:
        found = None
        for a in range(2, max_a):
            if pow(a, N - 1, N) != 1:
                continue
            if gcd(pow(a, (N - 1) // r, N) - 1, N) == 1:
                found = a
                break
        if found is None:
            return None
        out[r] = found
    return out


def pocklington_verify(N: int, F: int, rs, wit) -> bool:
    """Re-check a Pocklington certificate from scratch."""
    if N < 3 or N % 2 == 0:
        return False
    if (N - 1) % F != 0:
        return False
    R = (N - 1) // F
    if gcd(F, R) != 1:
        return False
    if F * F <= N:                      # need F > sqrt(N)
        return False
    m = F                               # rs must exhaust F, each prime
    for r in rs:
        if r >= MR_LIMIT or not is_prime_mr(r):
            return False
        while m % r == 0:
            m //= r
    if m != 1:
        return False
    for r in rs:
        a = wit.get(r) if isinstance(wit, dict) else wit.get(str(r))
        if a is None:
            return False
        if pow(a, N - 1, N) != 1:
            return False
        if gcd(pow(a, (N - 1) // r, N) - 1, N) != 1:
            return False
    return True


def smooth_numbers(A: int, B: int, primes, base: int = 4, limit: int = 400000):
    """Smooth multiples of `base` in [A, B], as (value, sorted distinct primes).

    Generated by multiplying small primes, so the factorisation is known without
    ever running a factorisation algorithm.
    """
    out, seen = [], set()

    def rec(i, cur, used):
        if len(out) >= limit:
            return
        if cur > B:
            return
        if cur >= A and cur not in seen:
            seen.add(cur)
            out.append((cur, sorted(used)))
        if i >= len(primes):
            return
        p, v = primes[i], cur
        rec(i + 1, cur, used)
        while v <= B // p:
            v *= p
            rec(i + 1, v, used | {p})

    rec(0, base, {2} if base % 2 == 0 else set())
    return out
