/- Sharp gaps-≤3 ladder, chunk 1: M ∈ [17078131210, 126165067026]. Generated by
   attempts/030-g3sharp/emit2.py. Build with `lean --tstack=131072` — `norm_num`
   primality on the 11–12 digit primes overflows the default thread stack. -/
import P287.StepG3S
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.GCD

set_option maxRecDepth 8000

namespace LadderG3S1

theorem chunk_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 17078131210 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 126165067026) :
    4 ≤ PCI.max_gap k s := by
  by_cases c0 : s ⟨k - 1, by omega⟩ ≤ 46418357149
  · exact StepG3S.step_gap4_sharp (p := 5692709977) (q := 4269532483) (r := 17078129933) (n := 17078129931)
      (a := 3) (b := 4) (c := 1) (tp := 8) (tq := 10) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c0
  exact StepG3S.step_gap4_sharp (p := 15472782319) (q := 23209173479) (r := 46418346959) (n := 46418346957)
      (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 5) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)

#print axioms chunk_gap

end LadderG3S1
