/- Sharp gaps-≤3 ladder, chunk 0: M ∈ [42359618, 17078131209]. Generated by
   attempts/030-g3sharp/emit2.py. Build with `lean --tstack=131072` — `norm_num`
   primality on the 11–12 digit primes overflows the default thread stack. -/
import P287.StepG3S
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.GCD

set_option maxRecDepth 8000

namespace LadderG3S0

theorem chunk_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 42359618 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 17078131209) :
    4 ≤ PCI.max_gap k s := by
  by_cases c0 : s ⟨k - 1, by omega⟩ ≤ 115132251
  · exact StepG3S.step_gap4_sharp (p := 14119727) (q := 21179591) (r := 42359183) (n := 42359181)
      (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 5) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c0
  by_cases c1 : s ⟨k - 1, by omega⟩ ≤ 312927283
  · exact StepG3S.step_gap4_sharp (p := 28782863) (q := 38377151) (r := 57565727) (n := 115131452)
      (a := 4) (b := 3) (c := 2) (tp := 10) (tq := 8) (tr := 5)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c1
  by_cases c2 : s ⟨k - 1, by omega⟩ ≤ 850535914
  · exact StepG3S.step_gap4_sharp (p := 156463561) (q := 104309041) (r := 78231781) (n := 312927122)
      (a := 2) (b := 3) (c := 4) (tp := 5) (tq := 8) (tr := 10)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c2
  by_cases c3 : s ⟨k - 1, by omega⟩ ≤ 2311754456
  · exact StepG3S.step_gap4_sharp (p := 283511707) (q := 425267561) (r := 850535123) (n := 850535121)
      (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 5) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c3
  by_cases c4 : s ⟨k - 1, by omega⟩ ≤ 6283348203
  · exact StepG3S.step_gap4_sharp (p := 770584769) (q := 577938577) (r := 2311754309) (n := 2311754307)
      (a := 3) (b := 4) (c := 1) (tp := 8) (tq := 10) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c4
  exact StepG3S.step_gap4_sharp (p := 6283344817) (q := 3141672409) (r := 2094448273) (n := 6283344817)
      (a := 1) (b := 2) (c := 3) (tp := 2) (tq := 5) (tr := 8)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)

#print axioms chunk_gap

end LadderG3S0
