/- Erdős-#287's machinery applied to gaps <= 3, generated by
   attempts/018-triples/gen_g3.py. -/
import P287.StepG3
import Mathlib.Tactic.NormNum.Prime

namespace LadderG3

/-- **For gaps ≤ 3 there is no representation of 1 with largest term M in
    [386, 42359617]** — stated as: any such representation has max_gap ≥ 4. -/
theorem g3_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 386 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 42359617) :
    4 ≤ PCI.max_gap k s := by
  by_cases c0 : s ⟨k - 1, by omega⟩ ≤ 634
  · exact StepG3.step_gap4 (p := 127) (q := 191) (r := 383) (n := 381) (a := 3) (b := 2) (c := 1) (tp := 4) (tq := 4) (tr := 4)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c0
  by_cases c1 : s ⟨k - 1, by omega⟩ ≤ 904
  · exact StepG3.step_gap4 (p := 541) (q := 271) (r := 181) (n := 541) (a := 1) (b := 2) (c := 3) (tp := 4) (tq := 4) (tr := 4)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c1
  by_cases c2 : s ⟨k - 1, by omega⟩ ≤ 1464
  · exact StepG3.step_gap4 (p := 877) (q := 439) (r := 293) (n := 877) (a := 1) (b := 2) (c := 3) (tp := 5) (tq := 4) (tr := 4)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c2
  by_cases c3 : s ⟨k - 1, by omega⟩ ≤ 2394
  · exact StepG3.step_gap4 (p := 479) (q := 719) (r := 1439) (n := 1437) (a := 3) (b := 2) (c := 1) (tp := 4) (tq := 5) (tr := 5)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c3
  by_cases c4 : s ⟨k - 1, by omega⟩ ≤ 4037
  · exact StepG3.step_gap4 (p := 2017) (q := 1009) (r := 673) (n := 2017) (a := 1) (b := 2) (c := 3) (tp := 5) (tq := 5) (tr := 5)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c4
  by_cases c5 : s ⟨k - 1, by omega⟩ ≤ 7553
  · exact StepG3.step_gap4 (p := 1259) (q := 1889) (r := 3779) (n := 3777) (a := 3) (b := 2) (c := 1) (tp := 5) (tq := 5) (tr := 5)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c5
  by_cases c6 : s ⟨k - 1, by omega⟩ ≤ 14837
  · exact StepG3.step_gap4 (p := 7417) (q := 3709) (r := 2473) (n := 7417) (a := 1) (b := 2) (c := 3) (tp := 6) (tq := 5) (tr := 5)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c6
  by_cases c7 : s ⟨k - 1, by omega⟩ ≤ 33690
  · exact StepG3.step_gap4 (p := 14437) (q := 7219) (r := 4813) (n := 14437) (a := 1) (b := 2) (c := 3) (tp := 6) (tq := 6) (tr := 6)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c7
  by_cases c8 : s ⟨k - 1, by omega⟩ ≤ 76068
  · exact StepG3.step_gap4 (p := 10867) (q := 16301) (r := 32603) (n := 32601) (a := 3) (b := 2) (c := 1) (tp := 6) (tq := 6) (tr := 6)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c8
  by_cases c9 : s ⟨k - 1, by omega⟩ ≤ 176728
  · exact StepG3.step_gap4 (p := 25247) (q := 37871) (r := 75743) (n := 75741) (a := 3) (b := 2) (c := 1) (tp := 6) (tq := 7) (tr := 7)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c9
  by_cases c10 : s ⟨k - 1, by omega⟩ ≤ 436482
  · exact StepG3.step_gap4 (p := 58199) (q := 87299) (r := 174599) (n := 174597) (a := 3) (b := 2) (c := 1) (tp := 7) (tq := 7) (tr := 7)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c10
  by_cases c11 : s ⟨k - 1, by omega⟩ ≤ 1087042
  · exact StepG3.step_gap4 (p := 434821) (q := 217411) (r := 144941) (n := 434821) (a := 1) (b := 2) (c := 3) (tp := 8) (tq := 7) (tr := 7)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c11
  by_cases c12 : s ⟨k - 1, by omega⟩ ≤ 2717532
  · exact StepG3.step_gap4 (p := 362339) (q := 543509) (r := 1087019) (n := 1087017) (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 8) (tr := 8)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c12
  by_cases c13 : s ⟨k - 1, by omega⟩ ≤ 6781092
  · exact StepG3.step_gap4 (p := 904147) (q := 1356221) (r := 2712443) (n := 2712441) (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 8) (tr := 8)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c13
  by_cases c14 : s ⟨k - 1, by omega⟩ ≤ 16946842
  · exact StepG3.step_gap4 (p := 6778741) (q := 3389371) (r := 2259581) (n := 6778741) (a := 1) (b := 2) (c := 3) (tp := 9) (tq := 9) (tr := 8)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c14
  by_cases c15 : s ⟨k - 1, by omega⟩ ≤ 42359617
  · exact StepG3.step_gap4 (p := 16943851) (q := 4235963) (r := 5647951) (n := 16943851) (a := 1) (b := 4) (c := 3) (tp := 9) (tq := 9) (tr := 9)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)
  push_neg at c15
  omega

#print axioms g3_gap

end LadderG3
