/- The DOWNWARD ladder for Erdős #287: one contiguous kernel-verified range,
   anchored just above the small-M base case rather than floating at 1e28.
   Generated by attempts/012-downward/gen_ladder.py. -/
import P287.StepA
import Mathlib.Tactic.NormNum.Prime

namespace Ladder

/-- **#287 holds for every largest term M in [39, 382613443].**

    24 rungs, each a pair of consecutive integers both forced out of the
    representation by Lemma A′ at one of their prime factors. -/
theorem ladder_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 39 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 382613443) :
    3 ≤ PCI.max_gap k s := by
  by_cases c0 : s ⟨k - 1, by omega⟩ ≤ 75
  · exact StepA.step_gap (p := 37) (q := 19) (n := 37) (a := 1) (b := 2) (tp := 3) (tq := 3)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c0
  by_cases c1 : s ⟨k - 1, by omega⟩ ≤ 147
  · exact StepA.step_gap (p := 73) (q := 37) (n := 73) (a := 1) (b := 2) (tp := 3) (tq := 3)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c1
  by_cases c2 : s ⟨k - 1, by omega⟩ ≤ 211
  · exact StepA.step_gap (p := 53) (q := 107) (n := 106) (a := 2) (b := 1) (tp := 3) (tq := 4)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c2
  by_cases c3 : s ⟨k - 1, by omega⟩ ≤ 387
  · exact StepA.step_gap (p := 193) (q := 97) (n := 193) (a := 1) (b := 2) (tp := 4) (tq := 4)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c3
  by_cases c4 : s ⟨k - 1, by omega⟩ ≤ 765
  · exact StepA.step_gap (p := 191) (q := 383) (n := 382) (a := 2) (b := 1) (tp := 4) (tq := 4)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c4
  by_cases c5 : s ⟨k - 1, by omega⟩ ≤ 1515
  · exact StepA.step_gap (p := 757) (q := 379) (n := 757) (a := 1) (b := 2) (tp := 5) (tq := 4)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c5
  by_cases c6 : s ⟨k - 1, by omega⟩ ≤ 2973
  · exact StepA.step_gap (p := 743) (q := 1487) (n := 1486) (a := 2) (b := 1) (tp := 5) (tq := 5)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c6
  by_cases c7 : s ⟨k - 1, by omega⟩ ≤ 5925
  · exact StepA.step_gap (p := 1481) (q := 2963) (n := 2962) (a := 2) (b := 1) (tp := 5) (tq := 5)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c7
  by_cases c8 : s ⟨k - 1, by omega⟩ ≤ 11757
  · exact StepA.step_gap (p := 2939) (q := 5879) (n := 5878) (a := 2) (b := 1) (tp := 5) (tq := 6)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c8
  by_cases c9 : s ⟨k - 1, by omega⟩ ≤ 23465
  · exact StepA.step_gap (p := 3911) (q := 5867) (n := 11733) (a := 3) (b := 2) (tp := 5) (tq := 6)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c9
  by_cases c10 : s ⟨k - 1, by omega⟩ ≤ 46797
  · exact StepA.step_gap (p := 11699) (q := 23399) (n := 23398) (a := 2) (b := 1) (tp := 6) (tq := 6)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c10
  by_cases c11 : s ⟨k - 1, by omega⟩ ≤ 93485
  · exact StepA.step_gap (p := 23371) (q := 15581) (n := 46742) (a := 2) (b := 3) (tp := 6) (tq := 6)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c11
  by_cases c12 : s ⟨k - 1, by omega⟩ ≤ 186907
  · exact StepA.step_gap (p := 31151) (q := 46727) (n := 93453) (a := 3) (b := 2) (tp := 6) (tq := 7)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c12
  by_cases c13 : s ⟨k - 1, by omega⟩ ≤ 373783
  · exact StepA.step_gap (p := 62297) (q := 46723) (n := 186891) (a := 3) (b := 4) (tp := 7) (tq := 7)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c13
  by_cases c14 : s ⟨k - 1, by omega⟩ ≤ 747555
  · exact StepA.step_gap (p := 373777) (q := 186889) (n := 373777) (a := 1) (b := 2) (tp := 8) (tq := 7)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c14
  by_cases c15 : s ⟨k - 1, by omega⟩ ≤ 1494645
  · exact StepA.step_gap (p := 373661) (q := 747323) (n := 747322) (a := 2) (b := 1) (tp := 8) (tq := 8)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c15
  by_cases c16 : s ⟨k - 1, by omega⟩ ≤ 2989287
  · exact StepA.step_gap (p := 1494643) (q := 373661) (n := 1494643) (a := 1) (b := 4) (tp := 8) (tq := 8)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c16
  by_cases c17 : s ⟨k - 1, by omega⟩ ≤ 5978453
  · exact StepA.step_gap (p := 1494613) (q := 996409) (n := 2989226) (a := 2) (b := 3) (tp := 8) (tq := 8)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c17
  by_cases c18 : s ⟨k - 1, by omega⟩ ≤ 11956903
  · exact StepA.step_gap (p := 1992817) (q := 1494613) (n := 5978451) (a := 3) (b := 4) (tp := 8) (tq := 8)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c18
  by_cases c19 : s ⟨k - 1, by omega⟩ ≤ 23913453
  · exact StepA.step_gap (p := 5978363) (q := 11956727) (n := 11956726) (a := 2) (b := 1) (tp := 9) (tq := 9)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c19
  by_cases c20 : s ⟨k - 1, by omega⟩ ≤ 47826903
  · exact StepA.step_gap (p := 23913451) (q := 5978363) (n := 23913451) (a := 1) (b := 4) (tp := 9) (tq := 9)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c20
  by_cases c21 : s ⟨k - 1, by omega⟩ ≤ 95653443
  · exact StepA.step_gap (p := 47826721) (q := 23913361) (n := 47826721) (a := 1) (b := 2) (tp := 10) (tq := 9)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c21
  by_cases c22 : s ⟨k - 1, by omega⟩ ≤ 191306775
  · exact StepA.step_gap (p := 95653387) (q := 23913347) (n := 95653387) (a := 1) (b := 4) (tp := 10) (tq := 9)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c22
  by_cases c23 : s ⟨k - 1, by omega⟩ ≤ 382613443
  · exact StepA.step_gap (p := 63768907) (q := 95653361) (n := 191306721) (a := 3) (b := 2) (tp := 10) (tq := 10)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Nat.factorial]) (by norm_num [Nat.factorial])
      (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega)
  push_neg at c23
  omega

#print axioms ladder_gap

end Ladder
