/- Sharp gaps-≤3 ladder, chunk 2: M ∈ [126165067027, 342916605345]. Generated by
   attempts/030-g3sharp/emit2.py. Build with `lean --tstack=131072` — `norm_num`
   primality on the 11–12 digit primes overflows the default thread stack. -/
import P287.StepG3S
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.GCD

set_option maxRecDepth 8000

namespace LadderG3S2

theorem chunk_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 126165067027 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 342916605345) :
    4 ≤ PCI.max_gap k s := by
  exact StepG3S.step_gap4_sharp (p := 42055016599) (q := 63082524899) (r := 126165049799) (n := 126165049797)
      (a := 3) (b := 2) (c := 1) (tp := 8) (tq := 5) (tr := 2)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)

#print axioms chunk_gap

end LadderG3S2
