/- Sharp gaps-≤3 ladder, chunk 3: M ∈ [342916605346, 932047325282]. Generated by
   attempts/030-g3sharp/emit2.py. Build with `lean --tstack=131072` — `norm_num`
   primality on the 11–12 digit primes overflows the default thread stack. -/
import P287.StepG3S
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.GCD

set_option maxRecDepth 8000

namespace LadderG3S3

theorem chunk_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 342916605346 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 932047325282) :
    4 ≤ PCI.max_gap k s := by
  exact StepG3S.step_gap4_sharp (p := 171458301193) (q := 114305534129) (r := 85729150597) (n := 342916602386)
      (a := 2) (b := 3) (c := 4) (tp := 5) (tq := 8) (tr := 10)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [LemAGen.lcmUpto, Nat.lcm]) (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num [LemAGen.lcmUpto, Nat.lcm])
      (by norm_num) (by norm_num) (by norm_num) hk s hmono h1 hsum
      (by omega) (by omega) (by omega) (by omega) (by omega)

#print axioms chunk_gap

end LadderG3S3
