/- The low end of the ladder: M in [9, 38], where rule A alone is not enough
   and the prime-power rule B supplies the missing exclusions.
   Generated by attempts/012-downward/gen_low.py. -/
import P287.StepAB
import Mathlib.Tactic.NormNum.Prime

namespace LowLadder

/-- **#287 holds for every largest term M in [9, 38].** -/
theorem low_gap {k : ℕ} (hk : 2 ≤ k) (s : Fin k → ℕ)
    (hmono : StrictMono s) (h1 : 1 < s ⟨0, by omega⟩)
    (hsum : ∑ i : Fin k, ((s i : ℚ))⁻¹ = 1)
    (hlo : 9 ≤ s ⟨k - 1, by omega⟩)
    (hhi : s ⟨k - 1, by omega⟩ ≤ 38) :
    3 ≤ PCI.max_gap k s := by
  by_cases c0 : s ⟨k - 1, by omega⟩ ≤ 15
  · refine StepAB.gap_of_excl (n := 7) hk s hmono h1 hsum (by omega) (by omega) ?_ ?_
    · exact StepAB.notTermA (p := 7) (t := 2) (n := 7) (a := 1) (by norm_num) (by norm_num)
        (by norm_num [Nat.factorial]) (by norm_num) hk s hmono h1 hsum (by omega)
    · exact StepAB.notTermB (q := 2) (e := 3) (n := 8) (by norm_num) (by norm_num) (by norm_num)
        hk s hmono h1 hsum (by omega)
  push_neg at c0
  by_cases c1 : s ⟨k - 1, by omega⟩ ≤ 20
  · refine StepAB.gap_of_excl (n := 13) hk s hmono h1 hsum (by omega) (by omega) ?_ ?_
    · exact StepAB.notTermA (p := 13) (t := 2) (n := 13) (a := 1) (by norm_num) (by norm_num)
        (by norm_num [Nat.factorial]) (by norm_num) hk s hmono h1 hsum (by omega)
    · exact StepAB.notTermA (p := 7) (t := 2) (n := 14) (a := 2) (by norm_num) (by norm_num)
        (by norm_num [Nat.factorial]) (by norm_num) hk s hmono h1 hsum (by omega)
  push_neg at c1
  by_cases c2 : s ⟨k - 1, by omega⟩ ≤ 31
  · refine StepAB.gap_of_excl (n := 16) hk s hmono h1 hsum (by omega) (by omega) ?_ ?_
    · exact StepAB.notTermB (q := 2) (e := 4) (n := 16) (by norm_num) (by norm_num) (by norm_num)
        hk s hmono h1 hsum (by omega)
    · exact StepAB.notTermA (p := 17) (t := 2) (n := 17) (a := 1) (by norm_num) (by norm_num)
        (by norm_num [Nat.factorial]) (by norm_num) hk s hmono h1 hsum (by omega)
  push_neg at c2
  by_cases c3 : s ⟨k - 1, by omega⟩ ≤ 38
  · refine StepAB.gap_of_excl (n := 26) hk s hmono h1 hsum (by omega) (by omega) ?_ ?_
    · exact StepAB.notTermA (p := 13) (t := 2) (n := 26) (a := 2) (by norm_num) (by norm_num)
        (by norm_num [Nat.factorial]) (by norm_num) hk s hmono h1 hsum (by omega)
    · exact StepAB.notTermB (q := 3) (e := 3) (n := 27) (by norm_num) (by norm_num) (by norm_num)
        hk s hmono h1 hsum (by omega)
  push_neg at c3
  omega

#print axioms low_gap

end LowLadder
